"""create initial astrocast schema

Revision ID: e2461684f17c
Revises: 
Create Date: 2026-07-24 17:42:13.777004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2461684f17c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_fetch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'started'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('fetched_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inserted_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('started', 'success', 'partial', 'failed')", name=op.f('ck_api_fetch_logs_fetch_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_fetch_logs'))
    )
    op.create_index('ix_api_fetch_logs_source_started_at', 'api_fetch_logs', ['source', 'started_at'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('latitude', 'longitude', name='uq_locations_coordinates')
    )
    op.create_table('space_weather_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('deduplication_key', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_space_weather_alerts')),
    sa.UniqueConstraint('source', 'deduplication_key', name='uq_space_weather_alerts_source_dedup_key')
    )
    op.create_index('ix_space_weather_alerts_issued_at', 'space_weather_alerts', ['issued_at'], unique=False)
    op.create_table('space_weather_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('deduplication_key', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('station', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('numeric_value IS NOT NULL OR text_value IS NOT NULL', name=op.f('ck_space_weather_measurements_has_measurement_value')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_space_weather_measurements')),
    sa.UniqueConstraint('source', 'deduplication_key', name='uq_space_weather_measurements_source_dedup_key')
    )
    op.create_index('ix_space_weather_measurements_metric_observed_at', 'space_weather_measurements', ['metric_name', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_space_weather_measurements_metric_observed_at', table_name='space_weather_measurements')
    op.drop_table('space_weather_measurements')
    op.drop_index('ix_space_weather_alerts_issued_at', table_name='space_weather_alerts')
    op.drop_table('space_weather_alerts')
    op.drop_table('locations')
    op.drop_index('ix_api_fetch_logs_source_started_at', table_name='api_fetch_logs')
    op.drop_table('api_fetch_logs')
    # ### end Alembic commands ###
